In [27]:
import os
import pickle

SAVE_DIR = r"C:\Users\nb0801\Documents\GitHub\IDS-CAN-Bus-In-Vehicle-Networks-Based-on-the-Statistical-Characteristics-of-Attacks\saved_data"

with open(os.path.join(SAVE_DIR, "attack_train_dfs.pkl"), "rb") as f:
    attack_train_dfs = pickle.load(f)

with open(os.path.join(SAVE_DIR, "attack_test_dfs.pkl"), "rb") as f:
    attack_test_dfs = pickle.load(f)

with open(os.path.join(SAVE_DIR, "ambient_train_dfs.pkl"), "rb") as f:
    ambient_train_dfs = pickle.load(f)

with open(os.path.join(SAVE_DIR, "ambient_test_dfs.pkl"), "rb") as f:
    ambient_test_dfs = pickle.load(f)

with open(os.path.join(SAVE_DIR, "attack_train_data.pkl"), "rb") as f:
    attack_train_data = pickle.load(f)

with open(os.path.join(SAVE_DIR, "attack_test_data.pkl"), "rb") as f:
    attack_test_data = pickle.load(f)

with open(os.path.join(SAVE_DIR, "ambient_train_data.pkl"), "rb") as f:
    ambient_train_data = pickle.load(f)

with open(os.path.join(SAVE_DIR, "ambient_test_data.pkl"), "rb") as f:
    ambient_test_data = pickle.load(f)

with open(os.path.join(SAVE_DIR, "attack_train_labels.pkl"), "rb") as f:
    attack_train_labels = pickle.load(f)

with open(os.path.join(SAVE_DIR, "attack_test_labels.pkl"), "rb") as f:
    attack_test_labels = pickle.load(f)

with open(os.path.join(SAVE_DIR, "ambient_train_labels.pkl"), "rb") as f:
    ambient_train_labels = pickle.load(f)

with open(os.path.join(SAVE_DIR, "ambient_test_labels.pkl"), "rb") as f:
    ambient_test_labels = pickle.load(f)

print(f"All datasets loaded successfully from '{SAVE_DIR}/'")

All datasets loaded successfully from 'C:\Users\nb0801\Documents\GitHub\IDS-CAN-Bus-In-Vehicle-Networks-Based-on-the-Statistical-Characteristics-of-Attacks\saved_data/'


In [51]:
attack_train_data

{'correlated_signal_attack_1': array([[  5, 225, 137, ..., 255, 236, 128],
        [  2, 139,   0, ...,   0,   0,   0],
        [  0, 208,  10, ...,   3,   7,   0],
        ...,
        [  0,  51,  23, ..., 128,   7, 208],
        [  2, 116,  81, ..., 124, 142, 185],
        [  6, 224,  89, ...,   0, 255, 255]], shape=(41580, 10)),
 'correlated_signal_attack_1_masquerade': array([[  5, 225, 137, ..., 255, 236, 128],
        [  2, 139,   0, ...,   0,   0,   0],
        [  0, 208,  10, ...,   3,   7,   0],
        ...,
        [  0,  51,  23, ..., 128,   7, 208],
        [  2, 116,  81, ..., 124, 142, 185],
        [  6, 224,  89, ...,   0, 255, 255]], shape=(39911, 10)),
 'correlated_signal_attack_2': array([[  2, 225,   0, ...,   0,   0,   4],
        [  3,  84,  32, ...,   6,  44,   0],
        [  5, 225, 137, ..., 255, 176, 128],
        ...,
        [  0,  51,   0, ...,   0,   7, 208],
        [  2, 116,   0, ..., 124, 142, 185],
        [  6, 224,  89, ...,   0, 255, 255]], shape=(

In [28]:
import builtins
import numpy as np


def sliding_windows_id_data(samples, labels, window_size=32, step=2, attack_labels=('T', 'D', 'F', 'S')):
    n = len(samples)

    if isinstance(attack_labels, str):
        attack_labels = (attack_labels,)

    windows = []
    window_labels = []
    next_id_datas = []
    

    for start in range(0, n - window_size, step):
        end = start + window_size
        window_slice = labels[start:end]

        windows.append(samples[start:end])
        next_id_datas.append(samples[end])

        matching_attack = builtins.next(
            (label for label in attack_labels if label in window_slice),
            'R'
        )
        window_labels.append(matching_attack)

    return (
        np.array(windows, dtype=np.uint8),
        np.array(next_id_datas, dtype=object),
        np.array(window_labels, dtype=object)
    )

In [41]:
# Combined training data
train_windows = []
train_labels = []

for name in attack_train_data:
    windows, _, labels = sliding_windows_id_data(
        attack_train_data[name],
        attack_train_labels[name]
    )

    train_windows.extend(windows)
    train_labels.extend(labels)
""""""
for name in ambient_train_data:
    windows, _, labels = sliding_windows_id_data(
        ambient_train_data[name],
        ambient_train_labels[name],
        attack_labels=(),
    )

    train_windows.extend(windows)
    train_labels.extend(labels)

# Convert to numpy arrays
train_windows = np.array(train_windows)
train_labels = np.array(train_labels)

In [42]:
# Combined testing data
test_windows = []
test_labels = []

for name in attack_test_data:
    windows, _, labels = sliding_windows_id_data(
        attack_test_data[name],
        attack_test_labels[name],
        window_size=32,
        step=2,
    )

    test_windows.extend(windows)
    test_labels.extend(labels)

for name in ambient_test_data:
    windows, _, labels = sliding_windows_id_data(
        ambient_test_data[name],
        ambient_test_labels[name],
        window_size=32,
        step=2,
        attack_labels=(),
    )

    test_windows.extend(windows)
    test_labels.extend(labels)#""""""

# Convert to numpy arrays
test_windows = np.array(test_windows)
test_labels = np.array(test_labels)

In [31]:
train_windows.shape

(607418, 32, 10)

In [43]:
t_indices = np.where(train_labels == 'T')[0]
print("Found 'T' labels:", len(t_indices))
print("First indices with 'T':", t_indices[:20])

Found 'T' labels: 577390
First indices with 'T': [ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [44]:
r_count = np.sum(test_labels == 'R')
t_count = np.sum(test_labels == 'T')
total = len(test_labels)

print("R count:", r_count)
print("T count:", t_count)
print("R proportion:", r_count / total)
print("T proportion:", t_count / total)
print("R/T ratio:", r_count / t_count if t_count else np.inf)

R count: 2421799
T count: 144502
R proportion: 0.9436924974895774
T proportion: 0.05630750251042259
R/T ratio: 16.759622704184025


In [45]:
attack_onehot_train = np.zeros((len(train_labels), 2), dtype=np.uint8)
attack_onehot_train[train_labels == 'R', 0] = 1
attack_onehot_train[train_labels == 'T', 1] = 1

print(attack_onehot_train[:10])

attack_onehot_test = np.zeros((len(test_labels), 2), dtype=np.uint8)
attack_onehot_test[test_labels == 'R', 0] = 1
attack_onehot_test[test_labels == 'T', 1] = 1

print(attack_onehot_test[:10])

[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]]


In [46]:
import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt

model = models.Sequential()
model.add(layers.Input(shape=(32, 10, 1)))
model.add(layers.Conv2D(32, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(2, activation='softmax'))


In [47]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

mod = model.fit(train_windows, attack_onehot_train, epochs=5, 
          batch_size=2000, 
          validation_split=0.2)
          
print(mod)

Epoch 1/5
4107/4107 ━━━━━━━━━━━━━━━━━━━━ 291s 70ms/step - accuracy: 0.9656 - loss: 0.1262 - val_accuracy: 0.9762 - val_loss: 0.0649
Epoch 2/5
4107/4107 ━━━━━━━━━━━━━━━━━━━━ 290s 70ms/step - accuracy: 0.9931 - loss: 0.0194 - val_accuracy: 0.9936 - val_loss: 0.0189
Epoch 3/5
4107/4107 ━━━━━━━━━━━━━━━━━━━━ 294s 71ms/step - accuracy: 0.9971 - loss: 0.0085 - val_accuracy: 0.9950 - val_loss: 0.0156
Epoch 4/5
4107/4107 ━━━━━━━━━━━━━━━━━━━━ 289s 70ms/step - accuracy: 0.9982 - loss: 0.0051 - val_accuracy: 0.9970 - val_loss: 0.0094
Epoch 5/5
4107/4107 ━━━━━━━━━━━━━━━━━━━━ 291s 71ms/step - accuracy: 0.9988 - loss: 0.0035 - val_accuracy: 0.9976 - val_loss: 0.0078


In [48]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import numpy as np

# Convert one-hot labels to integer labels
y_true = np.argmax(attack_onehot_test, axis=1)

# Predict probabilities and convert to integer labels
y_pred_probs = model.predict(test_windows)
y_pred = np.argmax(y_pred_probs, axis=1)

# Compute metrics
acc = accuracy_score(y_true, y_pred)
prec = precision_score(y_true, y_pred, pos_label=1)
rec = recall_score(y_true, y_pred, pos_label=1)
f1 = f1_score(y_true, y_pred, pos_label=1)

cm = confusion_matrix(y_true, y_pred)
tn, fp, fn, tp = cm.ravel()

fpr = fp / (fp + tn) if (fp + tn) else 0.0
fnr = fn / (fn + tp) if (fn + tp) else 0.0

print("Accuracy:", acc)
print("Precision:", prec)
print("Recall:", rec)
print("F1 score:", f1)
print("Confusion matrix:\n", cm)
print("False positive rate:", fpr)
print("False negative rate:", fnr)

80197/80197 ━━━━━━━━━━━━━━━━━━━━ 106s 1ms/step
Accuracy: 0.9964407916296646
Precision: 0.9827812491083912
Recall: 0.9534954533501266
F1 score: 0.9679168803433814
Confusion matrix:
 [[2419385    2414]
 [   6720  137782]]
False positive rate: 0.0009967796666857985
False negative rate: 0.04650454664987336


In [38]:
"""from tensorflow import keras

model = keras.models.load_model("saved_models/road_model.keras")
print("Loaded model from saved_models/road_model.keras")"""

'from tensorflow import keras\n\nmodel = keras.models.load_model("saved_models/road_model.keras")\nprint("Loaded model from saved_models/road_model.keras")'

In [49]:
from sklearn.metrics import classification_report, confusion_matrix, precision_score, recall_score, f1_score
import numpy as np

# Predict
y_true = np.argmax(attack_onehot_test, axis=1)
y_pred_probs = model.predict(test_windows, batch_size=2000)
y_pred = np.argmax(y_pred_probs, axis=1)

# Labels (modify if your label order differs)
labels = ['R', 'T']

# Classification report
print("Classification report:")
print(classification_report(y_true, y_pred, target_names=labels, digits=4))

# Confusion matrix
cm = confusion_matrix(y_true, y_pred)
print("Confusion matrix:")
print(cm)

# Per-class precision/recall/f1 and FPR/FNR
precisions = precision_score(y_true, y_pred, average=None, zero_division=0)
recalls = recall_score(y_true, y_pred, average=None, zero_division=0)
f1s = f1_score(y_true, y_pred, average=None, zero_division=0)

total = cm.sum()
for i, lbl in enumerate(labels):
    TP = cm[i, i]
    FN = cm[i, :].sum() - TP
    FP = cm[:, i].sum() - TP
    TN = total - TP - FP - FN
    fpr = FP / (FP + TN) if (FP + TN) else 0.0
    fnr = FN / (FN + TP) if (FN + TP) else 0.0
    print(f"{lbl}: precision={precisions[i]:.4f}, recall={recalls[i]:.4f}, f1={f1s[i]:.4f}, false positive rate={fpr:.4f}, false negative rate={fnr:.4f}")

1284/1284 ━━━━━━━━━━━━━━━━━━━━ 24s 19ms/step
Classification report:
              precision    recall  f1-score   support

           R     0.9972    0.9990    0.9981   2421799
           T     0.9828    0.9535    0.9679    144502

    accuracy                         0.9964   2566301
   macro avg     0.9900    0.9762    0.9830   2566301
weighted avg     0.9964    0.9964    0.9964   2566301

Confusion matrix:
[[2419385    2414]
 [   6720  137782]]
R: precision=0.9972, recall=0.9990, f1=0.9981, false positive rate=0.0465, false negative rate=0.0010
T: precision=0.9828, recall=0.9535, f1=0.9679, false positive rate=0.0010, false negative rate=0.0465


In [50]:
import os
from tensorflow import keras

os.makedirs("saved_models", exist_ok=True)
model.save(os.path.join("saved_models", "road_model_3.keras"))
print("Saved model to saved_models/road_model_3.keras")

Saved model to saved_models/road_model_3.keras


In [ ]:
"""import tensorflow as tf


converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

with open("road_model.tflite", "wb") as f:
    f.write(tflite_model)"""

INFO:tensorflow:Assets written to: C:\Users\nb0801\AppData\Local\Temp\tmpts_mlj9a\assets


INFO:tensorflow:Assets written to: C:\Users\nb0801\AppData\Local\Temp\tmpts_mlj9a\assets


Saved artifact at 'C:\Users\nb0801\AppData\Local\Temp\tmpts_mlj9a'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 32, 10, 1), dtype=tf.float32, name='keras_tensor')
Output Type:
  TensorSpec(shape=(None, 2), dtype=tf.float32, name=None)
Captures:
  1860923806864: TensorSpec(shape=(), dtype=tf.resource, name=None)
  1860923808016: TensorSpec(shape=(), dtype=tf.resource, name=None)
  1860923807632: TensorSpec(shape=(), dtype=tf.resource, name=None)
  1860923808400: TensorSpec(shape=(), dtype=tf.resource, name=None)
  1860923809744: TensorSpec(shape=(), dtype=tf.resource, name=None)
  1860923810512: TensorSpec(shape=(), dtype=tf.resource, name=None)
  1860923810128: TensorSpec(shape=(), dtype=tf.resource, name=None)
  1860923809552: TensorSpec(shape=(), dtype=tf.resource, name=None)
