In [14]:
import os
import pickle

SAVE_DIR = r"C:\Users\nb0801\Documents\GitHub\IDS-CAN-Bus-In-Vehicle-Networks-Based-on-the-Statistical-Characteristics-of-Attacks\saved_data"

with open(os.path.join(SAVE_DIR, "attack_train_dfs.pkl"), "rb") as f:
    attack_train_dfs = pickle.load(f)

with open(os.path.join(SAVE_DIR, "attack_test_dfs.pkl"), "rb") as f:
    attack_test_dfs = pickle.load(f)

with open(os.path.join(SAVE_DIR, "ambient_train_dfs.pkl"), "rb") as f:
    ambient_train_dfs = pickle.load(f)

with open(os.path.join(SAVE_DIR, "ambient_test_dfs.pkl"), "rb") as f:
    ambient_test_dfs = pickle.load(f)

with open(os.path.join(SAVE_DIR, "attack_train_data.pkl"), "rb") as f:
    attack_train_data = pickle.load(f)

with open(os.path.join(SAVE_DIR, "attack_test_data.pkl"), "rb") as f:
    attack_test_data = pickle.load(f)

with open(os.path.join(SAVE_DIR, "ambient_train_data.pkl"), "rb") as f:
    ambient_train_data = pickle.load(f)

with open(os.path.join(SAVE_DIR, "ambient_test_data.pkl"), "rb") as f:
    ambient_test_data = pickle.load(f)

with open(os.path.join(SAVE_DIR, "attack_train_labels.pkl"), "rb") as f:
    attack_train_labels = pickle.load(f)

with open(os.path.join(SAVE_DIR, "attack_test_labels.pkl"), "rb") as f:
    attack_test_labels = pickle.load(f)

with open(os.path.join(SAVE_DIR, "ambient_train_labels.pkl"), "rb") as f:
    ambient_train_labels = pickle.load(f)

with open(os.path.join(SAVE_DIR, "ambient_test_labels.pkl"), "rb") as f:
    ambient_test_labels = pickle.load(f)

print(f"All datasets loaded successfully from '{SAVE_DIR}/'")

All datasets loaded successfully from 'C:\Users\nb0801\Documents\GitHub\IDS-CAN-Bus-In-Vehicle-Networks-Based-on-the-Statistical-Characteristics-of-Attacks\saved_data/'


In [15]:
import builtins
import numpy as np


def sliding_windows_id_data(samples, labels, window_size=32, step=2, attack_labels=('T', 'D', 'F', 'S')):
    n = len(samples)

    if isinstance(attack_labels, str):
        attack_labels = (attack_labels,)

    windows = []
    window_labels = []
    next_id_datas = []
    

    for start in range(0, n - window_size, step):
        end = start + window_size
        window_slice = labels[start:end]

        windows.append(samples[start:end])
        next_id_datas.append(samples[end])

        matching_attack = builtins.next(
            (label for label in attack_labels if label in window_slice),
            'R'
        )
        window_labels.append(matching_attack)

    return (
        np.array(windows, dtype=np.uint8),
        np.array(next_id_datas, dtype=object),
        np.array(window_labels, dtype=object)
    )

In [55]:
# Combined training data
train_windows = []
train_labels = []

for name in attack_train_data:
    windows, _, labels = sliding_windows_id_data(
        attack_train_data[name],
        attack_train_labels[name]
    )

    train_windows.extend(windows)
    train_labels.extend(labels)
"""
for name in ambient_train_data:
    windows, _, labels = sliding_windows_id_data(
        ambient_train_data[name],
        ambient_train_labels[name],
        attack_labels=(),
    )

    train_windows.extend(windows)
    train_labels.extend(labels)"""

# Convert to numpy arrays
train_windows = np.array(train_windows)
train_labels = np.array(train_labels)

In [ ]:
# Combined testing data
test_windows = []
test_labels = []

for name in attack_test_data:
    windows, _, labels = sliding_windows_id_data(
        attack_test_data[name],
        attack_test_labels[name],
        window_size=32,
        step=2,
    )

    test_windows.extend(windows)
    test_labels.extend(labels)

"""for name in ambient_test_data:
    windows, _, labels = sliding_windows_id_data(
        ambient_test_data[name],
        ambient_test_labels[name],
        window_size=32,
        step=2,
        attack_labels=(),
    )

    test_windows.extend(windows)
    test_labels.extend(labels)"""

# Convert to numpy arrays
test_windows = np.array(test_windows)
test_labels = np.array(test_labels)

In [75]:
train_windows.shape

(1637493, 32, 10)

In [64]:
t_indices = np.where(train_labels == 'T')[0]
print("Found 'T' labels:", len(t_indices))
print("First indices with 'T':", t_indices[:20])

Found 'T' labels: 748466
First indices with 'T': [334214 334215 334216 334217 334218 334219 334220 334221 334222 334223
 334224 334225 334226 334227 334228 334229 334230 334231 334232 334233]


In [83]:
r_count = np.sum(test_labels == 'R')
t_count = np.sum(test_labels == 'T')
total = len(test_labels)

print("R count:", r_count)
print("T count:", t_count)
print("R proportion:", r_count / total)
print("T proportion:", t_count / total)
print("R/T ratio:", r_count / t_count if t_count else np.inf)

R count: 389627
T count: 19349
R proportion: 0.9526891553538593
T proportion: 0.047310844646140604
R/T ratio: 20.136802935552225


In [66]:
attack_onehot_train = np.zeros((len(train_labels), 2), dtype=np.uint8)
attack_onehot_train[train_labels == 'R', 0] = 1
attack_onehot_train[train_labels == 'T', 1] = 1

print(attack_onehot_train[:10])

attack_onehot_test = np.zeros((len(test_labels), 2), dtype=np.uint8)
attack_onehot_test[test_labels == 'R', 0] = 1
attack_onehot_test[test_labels == 'T', 1] = 1

print(attack_onehot_test[:10])

[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]]
[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]]


In [80]:
import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt

model = models.Sequential()
model.add(layers.Input(shape=(32, 10, 1)))
model.add(layers.Conv2D(32, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(2, activation='softmax'))


In [81]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

mod = model.fit(train_windows, attack_onehot_train, epochs=5, 
          batch_size=2000, 
          validation_split=0.2)
          
print(mod)

Epoch 1/5
655/655 ━━━━━━━━━━━━━━━━━━━━ 55s 82ms/step - accuracy: 0.8023 - loss: 0.6643 - val_accuracy: 0.5990 - val_loss: 0.8973
Epoch 2/5
655/655 ━━━━━━━━━━━━━━━━━━━━ 52s 79ms/step - accuracy: 0.9056 - loss: 0.2269 - val_accuracy: 0.6414 - val_loss: 0.8613
Epoch 3/5
655/655 ━━━━━━━━━━━━━━━━━━━━ 52s 79ms/step - accuracy: 0.9381 - loss: 0.1535 - val_accuracy: 0.6472 - val_loss: 1.0329
Epoch 4/5
655/655 ━━━━━━━━━━━━━━━━━━━━ 53s 81ms/step - accuracy: 0.9569 - loss: 0.1091 - val_accuracy: 0.6333 - val_loss: 1.1660
Epoch 5/5
655/655 ━━━━━━━━━━━━━━━━━━━━ 52s 79ms/step - accuracy: 0.9680 - loss: 0.0815 - val_accuracy: 0.6211 - val_loss: 1.6067


In [82]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import numpy as np

# Convert one-hot labels to integer labels
y_true = np.argmax(attack_onehot_test, axis=1)

# Predict probabilities and convert to integer labels
y_pred_probs = model.predict(test_windows)
y_pred = np.argmax(y_pred_probs, axis=1)

# Compute metrics
acc = accuracy_score(y_true, y_pred)
prec = precision_score(y_true, y_pred, pos_label=1)
rec = recall_score(y_true, y_pred, pos_label=1)
f1 = f1_score(y_true, y_pred, pos_label=1)

cm = confusion_matrix(y_true, y_pred)
tn, fp, fn, tp = cm.ravel()

fpr = fp / (fp + tn) if (fp + tn) else 0.0
fnr = fn / (fn + tp) if (fn + tp) else 0.0

print("Accuracy:", acc)
print("Precision:", prec)
print("Recall:", rec)
print("F1 score:", f1)
print("Confusion matrix:\n", cm)
print("False positive rate:", fpr)
print("False negative rate:", fnr)

12781/12781 ━━━━━━━━━━━━━━━━━━━━ 20s 2ms/step
Accuracy: 0.936526837760651
Precision: 0.42468094804010936
Recall: 0.9630988681585612
F1 score: 0.5894447168229768
Confusion matrix:
 [[364382  25245]
 [   714  18635]]
False positive rate: 0.06479273766961735
False negative rate: 0.03690113184143883


In [ ]:
"""from tensorflow import keras

model = keras.models.load_model("saved_models/road_model.keras")
print("Loaded model from saved_models/road_model.keras")"""

Loaded model from saved_models/road_model.keras


In [47]:
from sklearn.metrics import classification_report, confusion_matrix, precision_score, recall_score, f1_score
import numpy as np

# Predict
y_true = np.argmax(attack_onehot_test, axis=1)
y_pred_probs = model.predict(test_windows, batch_size=2000)
y_pred = np.argmax(y_pred_probs, axis=1)

# Labels (modify if your label order differs)
labels = ['R', 'T']

# Classification report
print("Classification report:")
print(classification_report(y_true, y_pred, target_names=labels, digits=4))

# Confusion matrix
cm = confusion_matrix(y_true, y_pred)
print("Confusion matrix:")
print(cm)

# Per-class precision/recall/f1 and FPR/FNR
precisions = precision_score(y_true, y_pred, average=None, zero_division=0)
recalls = recall_score(y_true, y_pred, average=None, zero_division=0)
f1s = f1_score(y_true, y_pred, average=None, zero_division=0)

total = cm.sum()
for i, lbl in enumerate(labels):
    TP = cm[i, i]
    FN = cm[i, :].sum() - TP
    FP = cm[:, i].sum() - TP
    TN = total - TP - FP - FN
    fpr = FP / (FP + TN) if (FP + TN) else 0.0
    fnr = FN / (FN + TP) if (FN + TP) else 0.0
    print(f"{lbl}: precision={precisions[i]:.4f}, recall={recalls[i]:.4f}, f1={f1s[i]:.4f}, false positive rate={fpr:.4f}, false negative rate={fnr:.4f}")

ValueError: Exception encountered when calling Sequential.call().

Input 0 with name 'None' of layer 'dense' is incompatible with the layer: expected axis -1 of input shape to have value 3712, but received input with shape (2000, 1664)

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=(2000, 32, 10, 1), dtype=float32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>

In [ ]:
import os
from tensorflow import keras

os.makedirs("saved_models", exist_ok=True)
model.save(os.path.join("saved_models", "road_model.keras"))
print("Saved model to saved_models/road_model.keras")

Saved model to saved_models/road_model.keras


In [ ]:
import tensorflow as tf


converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

with open("road_model.tflite", "wb") as f:
    f.write(tflite_model)

INFO:tensorflow:Assets written to: C:\Users\nb0801\AppData\Local\Temp\tmpz2thlg95\assets


INFO:tensorflow:Assets written to: C:\Users\nb0801\AppData\Local\Temp\tmpz2thlg95\assets


Saved artifact at 'C:\Users\nb0801\AppData\Local\Temp\tmpz2thlg95'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 64, 10, 1), dtype=tf.float32, name='input_layer')
Output Type:
  TensorSpec(shape=(None, 2), dtype=tf.float32, name=None)
Captures:
  2071605018448: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2071605018064: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2071610132624: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2071610130512: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2071610134544: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2071610135312: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2071610135120: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2071610135504: TensorSpec(shape=(), dtype=tf.resource, name=None)
